name: app_badge
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/hurelhuyag/app_badge

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
