name: build_badge
description: Badge to distinguish different builds. Such as staging, dev, production etc
version: 0.0.3
homepage: https://github.com/hurelhuyag/build_badge

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
